name: Create tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  create_tag:
    runs-on: ubuntu-latest
    name: Check and create tag

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setting up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Create tag
        run: |
          git tag -a ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"
          git push origin ${{ github.event.inputs.tag }}
